In [1]:
import numpy as np
import sympy as sp

In [2]:
#l = sqrt(L^2+A^2) LARGO/2 Y ANCHO/2
#r RADIO DE LA RUEDA
#v velocidad lineal ross
#w velocidad angular ross
# a alpha tg-1(L/A)
# b beta 90-a
v, w= sp.symbols("v w") 
p1,p2,p3,p4=sp.symbols("p1 p2 p3 p4")

pi=np.pi

r=10/100 #metros
La=56.22/2/100 #metors
An=42/2/100 #metros
la= np.sqrt(La**2+An**2)
a=np.arctan2(An,La)
b=pi/2-a


#LEFT FRONT
a1=a
b1=b

#LEFT BACK
a2=-(pi+a)
b2=-b

#RIGHT FRONT
a3=-a
b3=-(pi+b)

#RIGHT BACK
a4=pi+a
b4=b+pi

A= sp.Matrix([[sp.sin(a1+b1),-sp.cos(a1+b1),-la*sp.cos(b1)],
              [sp.cos(a1+b1),sp.sin(a1+b1),la*sp.sin(b1)],
              [sp.sin(a2+b2),-sp.cos(a2+b2),-la*sp.cos(b2)],
              [sp.cos(a2+b2),sp.sin(a2+b2),la*sp.sin(b2)],
              [sp.sin(a3+b3),-sp.cos(a3+b3),-la*sp.cos(b3)],
              [sp.cos(a3+b3),sp.sin(a3+b3),la*sp.sin(b3)],
              [sp.sin(a4+b4),-sp.cos(a4+b4),-la*sp.cos(b4)],
              [sp.cos(a4+b4),sp.sin(a4+b4),la*sp.sin(b4)]
              ])
B= sp.Matrix([[r,0,0,0],
              [0,0,0,0],
              [0,r,0,0],
              [0,0,0,0],
              [0,0,r,0],
              [0,0,0,0],
              [0,0,0,r],
              [0,0,0,0],
              ])

epsilon=sp.Matrix([[v,0,2.85*w]])

p=sp.Matrix([[p1,p2,p3,p4]])

# CINEMATICA INVERSA

In [3]:
#velocidades de las ruedas
B_psinv=(B.H * B) ** -1 * B.H # Moore–Penrose pseudoinverse
R= B_psinv * A 
# display(R)
dphi=R*epsilon.H
display(dphi)

Matrix([
[10.0*conjugate(v) - 5.985*conjugate(w)],
[10.0*conjugate(v) - 5.985*conjugate(w)],
[10.0*conjugate(v) + 5.985*conjugate(w)],
[10.0*conjugate(v) + 5.985*conjugate(w)]])

In [4]:
print(10*0.25-2.1*0.5)
print(10*0.25+2.1*0.5)

1.45
3.55


# CINEMATICA DIRECTA

In [5]:
from sympy import *
#velocidades de las ruedas
A_psinv=(A.H * A) ** -1 * A.H # Moore–Penrose pseudoinverse
R= A_psinv * B 

# display(R)

ep=R*p.H
ep=N(ep,2)
display(ep)


Matrix([
[         0.025*conjugate(p1) + 0.025*conjugate(p2) + 0.025*conjugate(p3) + 0.025*conjugate(p4)],
[-2.1e-18*conjugate(p1) + 4.0e-18*conjugate(p2) + 5.2e-18*conjugate(p3) - 7.1e-18*conjugate(p4)],
[        -0.043*conjugate(p1) - 0.043*conjugate(p2) + 0.043*conjugate(p3) + 0.043*conjugate(p4)]])

# COMPROBAR

In [6]:


#l = sqrt(L^2+A^2) LARGO/2 Y ANCHO/2
#r RADIO DE LA RUEDA
#v velocidad lineal ross
#w velocidad angular ross
# a alpha tg-1(L/A)
# b beta 90-a

r=10/100 #metros
La=56.2/2/100 #metros
An=42/2/100 #metros

la= np.sqrt(La**2+An**2) #metros

a=np.arctan2(An,La)
b=np.pi/2-a

print( r, v, w, a, b, An, La, la)

#LEFT FRONT
a1=a
b1=b

#LEFT BACK
a2=-(np.pi+a)
b2=-b

#RIGHT FRONT
a3=-a
b3=-(np.pi+b)

#RIGHT BACK
a4=np.pi+a
b4=b+np.pi


A= np.array([[np.sin(a1+b1),-np.cos(a1+b1),-la*np.cos(b1)],
              [np.cos(a1+b1),np.sin(a1+b1),la*np.sin(b1)],
              [np.sin(a2+b2),-np.cos(a2+b2),-la*np.cos(b2)],
              [np.cos(a2+b2),np.sin(a2+b2),la*np.sin(b2)],
              [np.sin(a3+b3),-np.cos(a3+b3),-la*np.cos(b3)],
              [np.cos(a3+b3),np.sin(a3+b3),la*np.sin(b3)],
              [np.sin(a4+b4),-np.cos(a4+b4),-la*np.cos(b4)],
              [np.cos(a4+b4),np.sin(a4+b4),la*np.sin(b4)]
              ])

B= np.array([[r,0,0,0],
              [0,0,0,0],
              [0,r,0,0],
              [0,0,0,0],
              [0,0,r,0],
              [0,0,0,0],
              [0,0,0,r],
              [0,0,0,0]
              ])



0.1 v w 0.6417907341783368 0.9290055926165598 0.21 0.281 0.3508005131125096


In [7]:
v= 0.2 #metros/seg
w= 0.1 #rad/seg

# #GANANCIA
# if(w>0):
#     k=0.89
# else:
#     k=-0.89

epsilon=np.array([[v,0,2.85*w]])

# Cinematica inversa

In [8]:
Le=10*v-5.985*w
Ri=10*v+5.985*w
dphi2=np.array([[Le,Ri]])
print(dphi2)

[[1.4015 2.5985]]


In [9]:
#velocidades de las ruedas
R= np.linalg.pinv(B).dot(A) 
# print(R)
dphi=R.dot(epsilon.T)
dphi=dphi+np.array([[0,0,0,0]]).T
print(dphi) #left front, left back, right front, right back

[[1.4015]
 [1.4015]
 [2.5985]
 [2.5985]]


# Cinematica directa

In [10]:
v2=0.025*(2*Le+2*Ri)
w2=-0.043*(2*Le-2*Ri)
ep2=np.array([[v2,0,w2]])
print(ep2)

[[0.2      0.       0.102942]]


In [11]:
#velocidades de las ruedas
R= np.linalg.pinv(A).dot(B) 
# print(R)

# dphi=np.array([[7.5,7.5,-7.5,-7.5]])
ep=R.dot(dphi) 
print(np.round(ep,2)) #v,0,w 

[[ 0.2]
 [-0. ]
 [ 0.1]]
